### ISSUE TITLE
JSON file can't be found

### ISSUE THREAD

**Issue by rosetree** [correctiv/apps.correctiv.org#1]
The [JSON File](https://apps.correctiv.org/media/justizgelder/data/bussgelder.json) for the Spendengerichte story, linked in the README, cannot be found.

**Comment by jsachse** [comment]
Thank you and sorry! We will fix it (missing file) as soon as possible.

**Comment by stefanw** [comment]
Fixed now, thanks @rosetree. Sorry for the delay, just back from holidays.

**Comment by rosetree** [comment]
Thank you @stefanw for uploading the file.
